-- Embeds emmy_core.dll from the emmylua_debugger package into src/emmy.dll.h
-- as a byte array, so it can be written out at runtime.
rule("embed_emmy_dll")
    before_build(function (target)
        local pkg = target:pkg("emmylua_debugger")
        assert(pkg, "emmylua_debugger package not found")
        local dll = path.join(pkg:installdir(), "bin", "emmy_core.dll")
        assert(os.isfile(dll), "emmy_core.dll not found at " .. dll)
        local out = path.join(os.projectdir(), "src", "emmy.dll.h")

        -- Skip if up-to-date
        if os.isfile(out) and os.mtime(out) >= os.mtime(dll) then
            return
        end

        local data = io.readfile(dll, {encoding = "binary"})
        local lines = {
            "// Auto-generated by xmake. Do not edit.",
            "#pragma once",
            "#include <cstddef>",
            "#include <cstdint>",
            "",
            "inline constexpr std::uint8_t emmy_core_dll[] = {",
        }
        local buf = {}
        for i = 1, #data do
            buf[#buf + 1] = string.format("0x%02x,", data:byte(i))
            if i % 16 == 0 then
                lines[#lines + 1] = "    " .. table.concat(buf, "")
                buf = {}
            end
        end
        if #buf > 0 then
            lines[#lines + 1] = "    " .. table.concat(buf, "")
        end
        lines[#lines + 1] = "};"
        lines[#lines + 1] = string.format("inline constexpr std::size_t emmy_core_dll_size = %d;", #data)
        lines[#lines + 1] = ""
        io.writefile(out, table.concat(lines, "\n"))
        cprint("${cyan}[gen]${clear} src/emmy.dll.h (%d bytes)", #data)
    end)
rule_end()
